CREATE TABLE "companies" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "companies_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"drive_folder_id" text NOT NULL,
	"name" text NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "companies_drive_folder_id_unique" UNIQUE("drive_folder_id")
);
--> statement-breakpoint
CREATE TABLE "company_profiles" (
	"company_id" integer PRIMARY KEY NOT NULL,
	"country" text NOT NULL,
	"legal_name" text NOT NULL,
	"address" text NOT NULL,
	"ico" text NOT NULL,
	"dic" text NOT NULL,
	"ic_dph" text NOT NULL,
	"register_source" text NOT NULL,
	"saved_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "documents" (
	"id" text PRIMARY KEY NOT NULL,
	"drive_file_id" text NOT NULL,
	"receipt_uid" text,
	"company_id" integer NOT NULL,
	"month_key" text NOT NULL,
	"folder_slot" text NOT NULL,
	"decision" text,
	"not_relevant_reason" text,
	"decided_at" text,
	"extraction_status" text DEFAULT 'pending' NOT NULL,
	"extraction_failure_reason" text,
	"extraction_pipeline_version" integer,
	"extracted_payload_json" text DEFAULT '{}' NOT NULL,
	"confirmed_payload_json" text DEFAULT '{}' NOT NULL,
	"note" text,
	"exported_at" text,
	"export_batch" text,
	"export_number" text,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "drive_mutations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "drive_mutations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"kind" text NOT NULL,
	"drive_file_id" text NOT NULL,
	"company_id" integer NOT NULL,
	"previous_parent" text NOT NULL,
	"previous_name" text NOT NULL,
	"new_parent" text NOT NULL,
	"new_name" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"intended_at" text NOT NULL,
	"applied_at" text,
	"failure_message" text,
	"undone_at" text
);
--> statement-breakpoint
CREATE TABLE "events" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"timestamp" text NOT NULL,
	"company_id" integer,
	"actor" text NOT NULL,
	"type" text NOT NULL,
	"payload_json" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "files" (
	"drive_file_id" text PRIMARY KEY NOT NULL,
	"company_id" integer NOT NULL,
	"month_key" text NOT NULL,
	"folder_slot" text,
	"parent_id" text NOT NULL,
	"name" text NOT NULL,
	"mime_type" text NOT NULL,
	"drive_created_time" text NOT NULL,
	"first_seen_at" text NOT NULL,
	"last_seen_at" text NOT NULL,
	"deleted" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "month_folders" (
	"drive_folder_id" text PRIMARY KEY NOT NULL,
	"company_id" integer NOT NULL,
	"month_key" text NOT NULL,
	"name" text NOT NULL,
	"parent_id" text NOT NULL,
	"can_rename" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "months" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "months_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"company_id" integer NOT NULL,
	"month_key" text NOT NULL,
	"drive_folder_id" text NOT NULL,
	"closed_at" text,
	"opened_at" text,
	CONSTRAINT "months_drive_folder_id_unique" UNIQUE("drive_folder_id")
);
--> statement-breakpoint
CREATE TABLE "partners" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "partners_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"company_id" integer NOT NULL,
	"country" text NOT NULL,
	"ico" text NOT NULL,
	"legal_name" text NOT NULL,
	"street" text DEFAULT '' NOT NULL,
	"psc" text DEFAULT '' NOT NULL,
	"city" text DEFAULT '' NOT NULL,
	"dic" text DEFAULT '' NOT NULL,
	"ic_dph" text DEFAULT '' NOT NULL,
	"updated_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "settings" (
	"id" integer PRIMARY KEY NOT NULL,
	"drive_parent_folder_id" text,
	"canonical_folder_names_json" text NOT NULL,
	"movable_folder_names_json" text,
	"last_sweep_at" text,
	"auto_advance_after_decision" boolean DEFAULT false NOT NULL,
	"omega_t01_evidence_code" text DEFAULT 'OF' NOT NULL,
	"omega_t01_series_code" text DEFAULT 'OF' NOT NULL,
	"omega_t01_received_evidence_code" text DEFAULT 'DF' NOT NULL,
	"omega_t01_received_series_code" text DEFAULT 'DF' NOT NULL,
	"omega_t00_evidence_code" text DEFAULT 'IDk' NOT NULL,
	"omega_t00_series_code" text DEFAULT 'IDk' NOT NULL,
	"omega_t00_document_type_code" text DEFAULT '180' NOT NULL,
	"omega_t00_foreign_document_type_code" text DEFAULT '380' NOT NULL,
	"drive_watch_channel_id" text,
	"drive_watch_resource_id" text,
	"drive_watch_token" text,
	"drive_watch_expires_at" text
);
--> statement-breakpoint
ALTER TABLE "company_profiles" ADD CONSTRAINT "company_profiles_company_id_companies_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "documents" ADD CONSTRAINT "documents_drive_file_id_files_drive_file_id_fk" FOREIGN KEY ("drive_file_id") REFERENCES "public"."files"("drive_file_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "documents" ADD CONSTRAINT "documents_company_id_companies_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "drive_mutations" ADD CONSTRAINT "drive_mutations_company_id_companies_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "events" ADD CONSTRAINT "events_company_id_companies_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "files" ADD CONSTRAINT "files_company_id_companies_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "month_folders" ADD CONSTRAINT "month_folders_company_id_companies_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "months" ADD CONSTRAINT "months_company_id_companies_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "partners" ADD CONSTRAINT "partners_company_id_companies_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "documents_company_export_number" ON "documents" USING btree ("company_id","export_number");--> statement-breakpoint
CREATE INDEX "documents_drive_file_id" ON "documents" USING btree ("drive_file_id");--> statement-breakpoint
CREATE UNIQUE INDEX "documents_file_receipt" ON "documents" USING btree ("drive_file_id","receipt_uid");--> statement-breakpoint
CREATE INDEX "documents_company_month" ON "documents" USING btree ("company_id","month_key");--> statement-breakpoint
CREATE INDEX "events_company" ON "events" USING btree ("company_id","id");--> statement-breakpoint
CREATE INDEX "files_company_month" ON "files" USING btree ("company_id","month_key");--> statement-breakpoint
CREATE UNIQUE INDEX "partners_company_country_ico" ON "partners" USING btree ("company_id","country","ico");